export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_DATA: 'VIEW_DATA',
  VIEW_TIMETABLE: 'VIEW_TIMETABLE',
  VIEW_VERSIONS: 'VIEW_VERSIONS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
  MANAGE_DIVISIONS: 'MANAGE_DIVISIONS',
  MANAGE_SUBJECTS: 'MANAGE_SUBJECTS',
  MANAGE_FACULTY: 'MANAGE_FACULTY',
  MANAGE_CLASSROOMS: 'MANAGE_CLASSROOMS',
  MANAGE_TIME_SLOTS: 'MANAGE_TIME_SLOTS',
  MANAGE_AVAILABILITY: 'MANAGE_AVAILABILITY',
  MANAGE_REQUIREMENTS: 'MANAGE_REQUIREMENTS',
  MANAGE_DIVISION_SUBJECTS: 'MANAGE_DIVISION_SUBJECTS',
  GENERATE_TIMETABLE: 'GENERATE_TIMETABLE',
  EDIT_TIMETABLE: 'EDIT_TIMETABLE',
  VALIDATE_TIMETABLE: 'VALIDATE_TIMETABLE',
  RESOLVE_CONFLICTS: 'RESOLVE_CONFLICTS',
  PUBLISH_TIMETABLE: 'PUBLISH_TIMETABLE',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
};

export const ROLE_LABELS = {
  ADMINISTRATOR: 'Administrator',
  SCHEDULER: 'Scheduler',
  VIEWER: 'Viewer',
};

export const ROLE_PERMISSIONS = {
  ADMINISTRATOR: Object.values(PERMISSIONS),
  SCHEDULER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DATA,
    PERMISSIONS.VIEW_TIMETABLE,
    PERMISSIONS.VIEW_VERSIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_AVAILABILITY,
    PERMISSIONS.MANAGE_REQUIREMENTS,
    PERMISSIONS.MANAGE_DIVISION_SUBJECTS,
    PERMISSIONS.GENERATE_TIMETABLE,
    PERMISSIONS.EDIT_TIMETABLE,
    PERMISSIONS.VALIDATE_TIMETABLE,
    PERMISSIONS.RESOLVE_CONFLICTS,
    PERMISSIONS.PUBLISH_TIMETABLE,
  ],
  VIEWER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_DATA,
    PERMISSIONS.VIEW_TIMETABLE,
    PERMISSIONS.VIEW_VERSIONS,
    PERMISSIONS.VIEW_REPORTS,
  ],
};

export function normalizeRole(role) {
  const value = String(role || '').trim().toUpperCase();
  if (value === 'ADMIN' || value === 'ADMINISTRATOR') return 'ADMINISTRATOR';
  if (value === 'SCHEDULER') return 'SCHEDULER';
  if (value === 'VIEWER') return 'VIEWER';
  return null;
}

export function formatRoleLabel(role) {
  return ROLE_LABELS[normalizeRole(role)] || 'Viewer';
}

export function canAccess(role, permission) {
  const normalizedRole = normalizeRole(role);
  if (!normalizedRole) return false;
  return (ROLE_PERMISSIONS[normalizedRole] || []).includes(permission);
}
